### ISSUE TITLE
Change base file name(s) to prevent conflicts on routers also running hass itself

### ISSUE THREAD

**Issue by dynasticorpheus** [mueslo/openwrt_hass_devicetracker#10]
Change base file name(s) to prevent conflicts on routers also running hass itself

**Comment by mueslo** [comment]
Do people really run Home Assistant on OpenWRT?

**Comment by dynasticorpheus** [comment]
@mueslo  Yes I am running it on a Linksys WRT32X AC3200 and it's working great. The beefy specs of the device make this possible. 

See below load average whilst HASS is running **AND** casting the baby cam to chromecast via ffmpeg based rtsp to hls remuxing. (without transcoding anything of course) 

`Load Average	0.10, 0.11, 0.09`

**Comment by zxdavb** [comment]
> Do people really run Home Assistant on OpenWRT?

I run it in OpenWrt, but inside a LXC container (along with 4 other containers): `0.14, 0.07, 0.01`

**Comment by mueslo** [comment]
yeah, `hass_devicetracker` might be a more obvious name, unless you have any better ideas.

**Comment by dynasticorpheus** [comment]
@mueslo sounds great

**Comment by mueslo** [comment]
implemented in https://github.com/mueslo/openwrt_hass_devicetracker/commit/aa744cc58191dac246eebda0356441bd6ab1eb6b
