### ISSUE TITLE
Why not pass _location_name_ on connects and disconnects?

### ISSUE THREAD

**Issue by SaturnusDJ** [mueslo/openwrt_hass_devicetracker#17]
While exploring https://github.com/mueslo/openwrt_hass_devicetracker/issues/16 I was wondering why, when a connect or disconnect happens, the script sends a _consider_home_ value. Why not send the _location_name_,  home on connect, and _location_name_, away on disconnect.

Is there a specific reason for this to not break things?

**Comment by mueslo** [comment]
What's the difference between this and #16?

**Comment by SaturnusDJ** [comment]
Here the question is why not use _location_name_ instead of _consider_home_ and send _home_ and _not_home_ states, which should cause no problem at all on the Home Assistant side and will have instant effect.

**Comment by mueslo** [comment]
consider_home is required so devices that drop off the network temporarily are not marked as away. Other than that, I'm not sure how exactly consider_home and location_name and zones interact, depending on that HA might need to be patched before #16 is solvable anyway.

**Comment by SaturnusDJ** [comment]
Got it. I have read on the HA pages that _consider_home_ is mainly used for iPhone.

My conclusion so far with this program is:
1) iPhones that enter sleep mode and thus cannot be detected with NMAP/Ping tools do not disconnect from the router, and the router does not kick them, so they stay _home_.
2) Meanwhile, when a device moves out of range the router times it out after some minute and it will be marked _not_home_.
(Subject to change. Still discovering the ins and outs.)

Absolutely great. 🥂 

Anyone has a different experience?
