### ISSUE TITLE
curl POST fails - connection refused

### ISSUE THREAD

**Issue by nadnerb33** [mueslo/openwrt_hass_devicetracker#19]
I've set up the device tracker on my OpenWRT router (BTHH5) to update my HA instance that is accessed via a HTTPS duckdns URL.
The logs show the connection is being refused so I adapted the functions.sh script to print out the curl command so I can examine it/run on another device.
Example:
```
curl "https://xxx.duckdns.org:8123/api/services/device_tracker/see" -sfSX POST -H 'Content-Type: application/json' -H 'X-HA-Access: xxx' --data-binary '{"mac":"xxx","host_name":"","consider_home":"24:00","source_type":"router"}'
curl: (7) Failed to connect to xxx.duckdns.org port 8123: Connection refused
```
If I run this command on my laptop or from my RPi/HA it works and updates the status of my device in HA - this means my credentials and curl requests are correct and valid but the OpenWRT request is getting blocked somehow.

I noticed if I try something like this where there is no authentication required it still fails:
`curl https://xxx.duckdns.org/local/image.png`
It just cant access the duckdns URL...

Any suggestions? Do I need to install some additional packages to get this working?

**Comment by oxan** [comment]
This happens because the duckdns domain resolves to your external IP, and you can't access your external address from inside your network. You should point the device tracker at the internal IP of your HA instance.

**Comment by LR-brendan** [comment]
I see that makes sense, thanks for the reply.
Although in my instance pointing to the internal IP will not work as HA is setup for SSL with DuckDNS so it no longer allows access via the local IP address.

In the end I just tweaked the functions.sh to point to one of my webservers which relays the request to HA.

**Comment by nadnerb33** [comment]
I see that makes sense, thanks for the reply.
Although in my instance pointing to the internal IP will not work as HA is setup for SSL with DuckDNS so it no longer allows access via the local IP address.

In the end I just tweaked the functions.sh to point to one of my webservers which relays the request to HA.

**Comment by AlfredoCABA** [comment]
Your router will resolve to whatever you ask to:
```bash
uci add dhcp domain
uci set dhcp.@domain[-1].name=xxx.duckdns.org
uci set dhcp.@domain[-1].ip=192.168.1.15
uci commit dhcp
```
Those commands instruct your router to resolve xxx.duckdns.org to the internal IP of your HA instance.
May work also for all gadgets on your network which use your router to resolve DNS entries (Android uses 8.8.8.8)
Also avaliable on LuCI GUI,
