### ISSUE TITLE
Why is /usr/bin/hassd.sh running two times?

### ISSUE THREAD

**Issue by SaturnusDJ** [mueslo/openwrt_hass_devicetracker#26]
AP1: 2.4GHz & 5.0GHz. 
```
root@AP1:~# ps | grep hass
 1258 root      1252 S    /bin/sh /usr/bin/hassd.sh
 1635 root       936 S    hostapd_cli -iwlan1 -a/usr/lib/hass/push_event.sh
 1660 root       936 S    hostapd_cli -iwlan0 -a/usr/lib/hass/push_event.sh
 1721 root       936 S    hostapd_cli -iwlan1-1 -a/usr/lib/hass/push_event.sh
```

AP2: 5.0GHz only.
```
root@AP2:~# ps | grep hass
 1063 root      1252 S    /bin/sh /usr/bin/hassd.sh
 1111 root      1252 S    /bin/sh /usr/bin/hassd.sh
 1838 root       936 S    hostapd_cli -iwlan0 -a/usr/lib/hass/push_event.sh
```

**Comment by mueslo** [comment]
Sounds to me like you have 2 SSIDs on one frequency on the 2.4/5 AP.

SaturnusDJ <notifications@github.com> schrieb am Mo., 4. März 2019, 21:55:

**Comment by SaturnusDJ** [comment]
@mueslo 
Correct, and the `/usr/bin/hassd.sh` script is running once. Seems fine.

AP2 however... runs the script twice. Even after stopping, starting, rebooting, etc. Always twice in the `ps` output.

**Comment by mueslo** [comment]
Oops, misread your output, I'll think more about this.

SaturnusDJ <notifications@github.com> schrieb am Mo., 4. März 2019, 23:07:

**Comment by mueslo** [comment]
I think it's because of the subshell.
