### ISSUE TITLE
The released ipk hass_0.1.1-1_all.ipk is outdated

### ISSUE THREAD

**Issue by gjengeda** [mueslo/openwrt_hass_devicetracker#27]
Is it possible to release a newer version of the ipk package?

The doc is up to date, describing the token authorization option. However, when downloading and installing the latest released ipk, token authorization doesn't work. This confused me a bit until I noticed that the latest released ipk is actually too old and doesn't contain the code for token authorization.

**Comment by SamJongenelen** [comment]
You're right - i just discovered it too. Can someone make and upload please?

**Comment by SamJongenelen** [comment]
Ok. I've build it myself. You can get it from https://drive.google.com/open?id=1eqAdzuK6QzEhS6b_uJySU06b8qxAYSP-

**Comment by disrupted** [comment]
@SamJongenelen did you upload your build?

**Comment by SamJongenelen** [comment]
@disrupted no I didn't. My device still runs openwrt CC (very old version of busybox) so I've had to make too many adjustments... I've had no succes in compiling it on Azure - but was successful using a Docker image

**Comment by ohadlevy** [comment]
I compiled mine using docker as well, was fairly simple, you can find my package at https://gist.github.com/ohadlevy/1233111c01c9735a822cb2394817c5b4

**Comment by disrupted** [comment]
@ohadlevy thanks man!

**Comment by dewi-ny-je** [comment]
How to get the token?
