### ISSUE TITLE
Service sometimes stop working on OpenWRT 18.06

### ISSUE THREAD

**Issue by tyborall** [mueslo/openwrt_hass_devicetracker#3]
On OpenWRT the service hass sometimes stop working and it has then to be restarted with /etc/init.d/hass restart. I don't know what is the cause and even there are no log entries.

**Comment by mueslo** [comment]
Yeah, I've observed the same thing. I also don't know the cause though :(

**Comment by tyborall** [comment]
How can I support you to debug this issue? What can I do?

**Comment by mueslo** [comment]
I've since upgraded to 18.06 and haven't run into this issue again so far. Is this still a problem on your configuration?
