### ISSUE TITLE
Needs new release! No support for long-lived-tokens in latest release (0.1.1)

### ISSUE THREAD

**Issue by t413** [mueslo/openwrt_hass_devicetracker#35]
Looks like token support was added less than a week after publishing the last release version, 0.1.1. Not sure what the right build release procedure is, I'll try and do it for myself locally.. but it'd be really great to have an official release!

Figuring out that the released version wasn't the same as this (last updated 2018) master code took _way too long_ to debug and figure out..

**Comment by mackattack3k** [comment]
Check out #27

**Comment by mueslo** [comment]
Work is currently getting in the way of work on this package, I will
hopefully have a chance to implement all the suggestions in about 1.5
weeks. Sorry for the delay.

Marcus Hansson <notifications@github.com> schrieb am Di., 6. Aug. 2019,
20:06:

**Comment by tyborall** [comment]
Any news mueslo? :-)

It is not working anymore with Home Assistant 0.97:

`Fri Aug 23 21:30:13 2019 daemon.info hostapd: wlan1: STA xx:xx:xx:xx:xx:xx IEEE 802.11: associated (aid 1)
Fri Aug 23 21:30:13 2019 daemon.notice hostapd: wlan1: AP-STA-CONNECTED xx:xx:xx:xx:xx:xx
Fri Aug 23 21:30:13 2019 daemon.info hostapd: wlan1: STA xx:xx:xx:xx:xx:xx RADIUS: starting accounting session 7CC2188A11CD4E56
Fri Aug 23 21:30:13 2019 daemon.info hostapd: wlan1: STA xx:xx:xx:xx:xx:xx WPA: pairwise key handshake completed (RSN)
Fri Aug 23 21:30:13 2019 user.debug /usr/lib/hass/push_event.sh: push_event wlan1 AP-STA-CONNECTED xx:xx:xx:xx:xx:xx
Fri Aug 23 21:30:13 2019 user.debug /usr/lib/hass/push_event.sh: build_payload xx:xx:xx:xx:xx:xx  24:00
Fri Aug 23 21:30:13 2019 user.debug /usr/lib/hass/push_event.sh: post {"mac":"xx:xx:xx:xx:xx:xx","host_name":"","consider_home":"24:00","source_type":"router"}
Fri Aug 23 21:30:13 2019 user.err /usr/lib/hass/push_event.sh: post response curl: (22) The requested URL returned error: 401 Unauthorized
`

I have enabled and created long live access token for it and configured correctly on OpenWRT.

**Comment by partofthething** [comment]
Heads up for anyone using @mackattack3k's temporary fix, you also need to apply the fix mentioned in #29, which is here: https://github.com/quthla/openwrt_hass_devicetracker/commit/ea0f08d1f68d36107706f231d5c0cfa2c762441d or else the disconnect events will get missed. Just went through this and really got confused for a minute.

**Comment by blamaz** [comment]
Awaiting development on this

**Comment by keniji** [comment]
Also be waiting a new release here...
