### ISSUE TITLE
Still working after 0.94 known devices change?

### ISSUE THREAD

**Issue by SaturnusDJ** [mueslo/openwrt_hass_devicetracker#36]
Does this program still work for you when adding A NEW device?
I added it to known_devices.yaml, the program seems to report it correctly to HA according to the logs on OpenWRT, and even recognizes the name set in known_devices.yaml, but HA itself keeps reporting it as the MAC address in logbook etc. and thus binding it to a person also doesn't work.

So either I made a stupid mistake (for which I checked multiple times), or HA is missing some kind of link between the program reports and entity, and in that case maybe there is a workaround for that?

**Comment by Shulyaka** [comment]
Probably the device hostname was not detected by the time the report was sent. You can check that in OpenWRT logs (i.e. `logread` command).

To rename, just change the `name:` value in your `known_devices.yaml` and restart HA.

**Comment by SaturnusDJ** [comment]
It turns out it was a stupid mistake still... 🤦‍♂ 🤦‍♂ 🤦‍♂ 

The device was automatically added to known_devices.yaml as the MAC address. Although this behaviour is what I want, I didn't realize it happened.
