### ISSUE TITLE
Add initial delay until hostname is clear

### ISSUE THREAD

**Issue by mueslo** [mueslo/openwrt_hass_devicetracker#37]
When new devices enter the network, host names are not set yet, so the host name function does not actually return anything.

**Comment by quthla** [comment]
I'd suggest retrying once after 2 secs if hostname initially empty.

**Comment by mueslo** [comment]
Actually, I think the best way to implement this would be on the home assistant side - if the "friendly_name" is still the mac, it should be overwritten by the hostname.

**Comment by quthla** [comment]
Problem is not just the friendly name but also the entity id which will be the mac address in case there's no friendly name when the entity is first created.

I also don't think it's good to overwrite the friendly name. You'd need to check if it's actually a mac address then etc.

For these reasons imo it's better to fix it here because this is also what provides hass with incorret data in the first place.

**Comment by mueslo** [comment]
I disagree. This script cannot know if HA already knows about the existence
of a certain device, so it would have to delay it every time, defeating the
idea of being fast and event-driven.

>

**Comment by quthla** [comment]
> 
> 
> I'd suggest retrying once after 2 secs if hostname initially empty.

The important part being "retrying"

Pseudocode
```
if (!get_hostname) {
sleep 2
get_hostname
}
```

So only if there is no hostname at first try, it will be delayed. Which means in probably like 99% of all cases, it will behave just like it does now.

**Comment by ttimasdf** [comment]
One viable solution: monitor DHCP event and ignore hostapd event if there's no hostname found.
https://gist.github.com/jwalanta/53f55d03fcf5265938b64ffd361502d5

**Comment by ttimasdf** [comment]
Try my fork(in [modified](https://github.com/ttimasdf/openwrt_hass_devicetracker/blob/modified/packages/net/hass-tracker/files/functions.sh) branch) of the script, added some features for my own need.

- Listen dnsmasq DHCP events, report to HA after IP and hostname present.
- Currently script get IP of MAC address from ARP cache. Add another way to get from DHCP leases.
- Filter hostapd associate event, if hostname could not be found from nslookup or DHCP leases, ignore the event. (DHCP event will call the script, so no device will be missed)
- Add whitelist option so non-related devices could be filtered out.

**Comment by mueslo** [comment]
Fix merged in HA.

Edit: actually, I misunderstood the way HA saves its data, so it looks like it's not fixed, sadly...
